In [1]:
import numpy as np

In [13]:
a = np.ones((5,5),dtype= 'int32')
a

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [21]:
a[1:4,1:4] = 0
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [22]:
a[2,2] = 9
a

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [39]:
b = np.array([[2,2],[3,3]])
c = np.ones([2,2], dtype = int)
print(b)
print(c)
print(b+c)

[[2 2]
 [3 3]]
[[1 1]
 [1 1]]
[[3 3]
 [4 4]]


In [51]:
d = np.random.randint(10,size = (8,8))



array([3, 7])