# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [7]:
d = np.zeros([10],dtype = 'int32')
d

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [8]:
d[4] = 1
d

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int32)

#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
c = np.random.randint(10, 50, size= 10)
print(c)

[48 28 41 48 27 46 36 31 16 19]


#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [16]:
print(c[::-1])

[19 16 31 36 46 27 48 41 28 48]


#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [20]:
a = np.random.randint(0,9,size = (3,3))
print(a)

[[5 5 0]
 [2 5 7]
 [7 5 2]]


#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [24]:
vec = np.array([1,2,0,0,4,0])
print(vec[vec > 0])

[1 2 4]


#### 8. Create a 3x3x3 array with random values (★☆☆)

In [26]:
b = np.random.rand(3,3,3)
print(b)

[[[0.6622787  0.29945412 0.1391876 ]
  [0.98482211 0.63180411 0.33515726]
  [0.36782657 0.73989701 0.24865385]]

 [[0.39965003 0.36566845 0.6322745 ]
  [0.67909305 0.39886483 0.6281753 ]
  [0.86502527 0.93028015 0.05148227]]

 [[0.88381325 0.19701526 0.02525247]
  [0.35625551 0.3639948  0.47704309]
  [0.98833484 0.81731199 0.83963223]]]


#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [41]:
f = np.random.randint(0,10000, size= (10,10))
max = np.amax(f)
min = np.amin(f)
print(max,min)


9314 3


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [49]:
n = 30
g = np.random.randint(0,150, size= n)
sum = np.sum(g)
average = sum//n
print(average)

82


#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [52]:
border = np.ones([3,3], dtype = 'int')
border[1,1] = 0
print(border)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [54]:
new_border = np.zeros([5,5], dtype = 'int')
new_border[1:4,1:4] = border
print(new_border)

[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]


#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

0, nan, False, nan, True, False

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [74]:
t = np.zeros([5,5], dtype = 'int')
#t[4,0] = 1
#t[[3,4],[0,1]] = 2
#t[[2,3,4],[0,1,2]] = 3
t[[1,2,3,4],[0,1,2,3]] = [1,2,3,4]
print(t)



[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [89]:
g = np.unravel_index(100,(6,7,8))
print(g)

(1, 5, 4)


#### 16. Normalize a 5x5 random matrix (★☆☆)

In [105]:
y = np.random.randint(0,100, size= (5,5))
max, min = np.amax(y), np.amin(y)
y = (y-min)/(max-min)
print(y)

[[0.89361702 0.92553191 0.89361702 0.40425532 0.94680851]
 [0.61702128 0.60638298 0.84042553 0.04255319 0.38297872]
 [0.5106383  0.11702128 0.41489362 0.39361702 0.38297872]
 [1.         0.28723404 0.67021277 0.96808511 0.04255319]
 [0.         0.17021277 0.40425532 0.5        0.9787234 ]]


#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [117]:
g = np.random.randint(0,20, size= 20)
g[(3 < g) & (g <= 8)] *= -1
g

array([-5, -5,  2,  3, -8, -6, 15, 16, 10, 13, -7, 11, 19, 13, -6,  2,  9,
       -5, 18,  1])

#### 18. How to round away from zero a float array ? (★☆☆)

In [138]:
p = np.random.uniform(0,20,15)
p = np.ceil(p)
print(p)


[15.66254112 13.35555667  6.71340936 19.22219866 17.64647896 17.82250223
  4.25461972  4.44962489  3.67272444  8.68878078 13.77049379  0.5954241
  3.97064227  1.35905236  9.59328382]


#### 19. Find common values between two arrays? (★☆☆)

In [158]:
a = np.array([1,2,3,4,5,6,7,8])
b = np.random.randint(0,15,size= 8)
same = np.intersect1d(a,b)
print(same)

[1 2 4 5 7]


#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False because np.sqrt(-1) doesn't work

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [190]:
def generator(integers):
    array = np.array([])
    integer = 0
    while integer < integers:
        number = np.random.randint(1,10)
        array = np.append(array,number)
        integer += 1
    return array

print(generator(10))


[2. 8. 4. 8. 9. 2. 9. 8. 8. 3.]


#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [203]:
u = np.random.randint(1.1,20,10)
u
#idk if this is asking me to create an array from 0 to 1 and exclude the integers 0 and 1 or to create a vector of size
#10 that excludes 0 and 1. I put the latter above and former below.
u = np.random.rand(10)
u

array([0.55645799, 0.98910633, 0.93536835, 0.8319913 , 0.01955009,
       0.75596335, 0.88078955, 0.16895672, 0.88027773, 0.55251386])

#### 23. Create a random vector of size 10 and sort it (★★☆)

In [204]:
u = np.random.randint(0,10,15)
u = np.sort(u)
print(u)

[1 1 3 3 3 4 4 5 5 5 6 7 7 7 9]


#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [207]:
A = np.random.randint(0,10,15)
B = np.random.randint(0,10,15)
print(A==B)

[False False False False False False  True False False False False False
 False False False]


#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [214]:
D = np.random.randint(0,100,10)
max = np.max(D)
D[D == max] = 0
print(D)


[41 73 60 68 78  0  9 25 20  1]


#### 26. Find the closest value to random element in a vector? (★★☆)

In [220]:
M = np.random.uniform(0,10,1)
closest = np.round(M)
print(closest)

[3.]


#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

In [224]:
N = np.arange(10, dtype=np.float32)
N = N.astype(np.int32)
print(N)

[0 1 2 3 4 5 6 7 8 9]


#### 28. Sort an array by the nth column? (★★☆)

In [230]:
V = np.random.randint(0,15,size= (5,5))
n = 3
V = np.sort(V[:,n])
print(V)

[3 3 3 5 7]


#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

In [249]:
o = np.zeros([3,3], dtype= 'int')
np.nan in o


False

#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [267]:
vector = np.arange(1,6)
new_vector = np.zeros(3, dtype = 'int')
final = np.array([])
for i in range(5):
    final = np.append(final, vector[i])
    if i < 4:
        final = np.append(final, new_vector)

final = final.astype(np.int32)
print(final)

    


[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 31. Swap two rows of an array? (★★★)

In [268]:
A = np.array([1,2,3,4,5])
B = np.array([5,4,3,2,1])
C = A
A = B
B = C
print(A,B)

[5 4 3 2 1] [1 2 3 4 5]


#### 32. How to negate a boolean value inside an array? (★★★)

In [274]:
U = np.array([True,True,False,True,False])
print(~U)

[False False  True False  True]


#### 33. Find the most frequent value in an array?

In [291]:
L = np.random.randint(0,10,50)
print(np.bincount(L).argmax())

array([9, 6, 9, 5, 0, 2, 6, 9, 3, 1, 2, 3, 1, 0, 6, 2, 0, 2, 7, 5, 9, 5,
       6, 7, 8, 8, 8, 9, 1, 0, 3, 7, 1, 2, 6, 9, 7, 6, 1, 7, 0, 5, 6, 7,
       1, 9, 5, 1, 7, 9])

#### 34. Get the n largest values of an array (★★★)

In [312]:
def largest_values(n):
    array = np.random.randint(0,10,20)
    sorted_array = np.sort(array)
    max_values = sorted_array[-n:]
    return max_values

print(largest_values(8))

[4 5 6 7 7 8 8 9]


#### 35. Extract unique rows from a two dimensional array? (★★★)

In [326]:
def unique_row(n):
    array = np.random.uniform(0,8,size= (5,2))
    return array[[n]]

print(unique_row(3))

[[5.00849841 6.62674549]]


In [329]:
from numpy import*